apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventexporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  exporter.yaml: |
    route:
      match:
      routes:
        - match:
            - receiver: "alertmanager"
              type: "Warning"
              minCount: 10
        - match:
            - receiver: "alertmanager"
              type: "Normal"
              message: ".*?above target$"
        - match:
            - receiver: "alertmanager"
              type: "Normal"
              message: ".*?below target$"
    receiverConfigs:
      - name: alertmanager
