route:
  match:
  routes:
    - match:
        - receiver: "alertmanager"
          type: "Warning"
          count: 10
    - match:
        - receiver: "alertmanager"
          type: "Normal"
          reason: ".*?above target$"
    - match:
        - receiver: "alertmanager"
          type: "Normal"
          reason: ".*?below target$"
receiverConfigs:
  - name: alertmanager
    config:
      host: 10.49.18.83:9093
