route:
  match:
  routes:
    - match:
        - receiver: "alertmanager"
          type: "Warning"
          minCount: 10
    - match:
        - receiver: "alertmanager"
          type: "Normal"
          message: ".*?above target$"
    - match:
        - receiver: "alertmanager"
          type: "Normal"
          message: ".*?below target$"
receiverConfigs:
  - name: alertmanager
    config:
      host: 127.0.0.1:9093
      laybelLayout:
        app: "{{ .InvolvedObject.Labels.app }}"
        group: "{{ .InvolvedObject.Labels.sym-group }}"
      annotationLayout:
        group: "{{ .InvolvedObject.Labels.sym-group }}"
